/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct msgbuf {
	char m_xlator[32];
	char m_key[32];
	uint64_t m_value;
};
typedef struct msgbuf msgbuf;

typedef msgbuf msgtype;

struct memdesc {
	uint64_t mem_off;
	uint32_t mem_size;
	uint32_t mem_reserve;
};
typedef struct memdesc memdesc;

typedef memdesc mdtype;

struct bulkbuf {
	uint32_t b_size;
	char b_bulk[1024];
};
typedef struct bulkbuf bulkbuf;

typedef bulkbuf bulktype;

struct valuebuf {
	int err;
	union {
		msgtype retbuf;
	} valuebuf_u;
};
typedef struct valuebuf valuebuf;

struct retbulkbuf {
	int err;
	union {
		bulktype retbuf;
	} retbulkbuf_u;
};
typedef struct retbulkbuf retbulkbuf;

#define MANAGER 85155585
#define MANAGERVERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define GETKEYVALUE 11
extern  valuebuf * getkeyvalue_2(msgtype *, CLIENT *);
extern  valuebuf * getkeyvalue_2_svc(msgtype *, struct svc_req *);
#define SETKEYVALUE 12
extern  int * setkeyvalue_2(msgtype *, CLIENT *);
extern  int * setkeyvalue_2_svc(msgtype *, struct svc_req *);
#define GETBULK 13
extern  retbulkbuf * getbulk_2(mdtype *, CLIENT *);
extern  retbulkbuf * getbulk_2_svc(mdtype *, struct svc_req *);
#define GETXLINFO 14
extern  retbulkbuf * getxlinfo_2(msgtype *, CLIENT *);
extern  retbulkbuf * getxlinfo_2_svc(msgtype *, struct svc_req *);
#define GETSTATUS 21
extern  int * getstatus_2(void *, CLIENT *);
extern  int * getstatus_2_svc(void *, struct svc_req *);
#define GETDBLEVEL 22
extern  int * getdblevel_2(void *, CLIENT *);
extern  int * getdblevel_2_svc(void *, struct svc_req *);
#define SETDBLEVEL 23
extern  int * setdblevel_2(int *, CLIENT *);
extern  int * setdblevel_2_svc(int *, struct svc_req *);
#define GETOPMASK 24
extern  int * getopmask_2(int *, CLIENT *);
extern  int * getopmask_2_svc(int *, struct svc_req *);
#define SETOPMASK 25
extern  int * setopmask_2(int *, CLIENT *);
extern  int * setopmask_2_svc(int *, struct svc_req *);
#define RESETJOB 31
extern  int * resetjob_2(int *, CLIENT *);
extern  int * resetjob_2_svc(int *, struct svc_req *);
extern int manager_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETKEYVALUE 11
extern  valuebuf * getkeyvalue_2();
extern  valuebuf * getkeyvalue_2_svc();
#define SETKEYVALUE 12
extern  int * setkeyvalue_2();
extern  int * setkeyvalue_2_svc();
#define GETBULK 13
extern  retbulkbuf * getbulk_2();
extern  retbulkbuf * getbulk_2_svc();
#define GETXLINFO 14
extern  retbulkbuf * getxlinfo_2();
extern  retbulkbuf * getxlinfo_2_svc();
#define GETSTATUS 21
extern  int * getstatus_2();
extern  int * getstatus_2_svc();
#define GETDBLEVEL 22
extern  int * getdblevel_2();
extern  int * getdblevel_2_svc();
#define SETDBLEVEL 23
extern  int * setdblevel_2();
extern  int * setdblevel_2_svc();
#define GETOPMASK 24
extern  int * getopmask_2();
extern  int * getopmask_2_svc();
#define SETOPMASK 25
extern  int * setopmask_2();
extern  int * setopmask_2_svc();
#define RESETJOB 31
extern  int * resetjob_2();
extern  int * resetjob_2_svc();
extern int manager_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_msgbuf (XDR *, msgbuf*);
extern  bool_t xdr_msgtype (XDR *, msgtype*);
extern  bool_t xdr_memdesc (XDR *, memdesc*);
extern  bool_t xdr_mdtype (XDR *, mdtype*);
extern  bool_t xdr_bulkbuf (XDR *, bulkbuf*);
extern  bool_t xdr_bulktype (XDR *, bulktype*);
extern  bool_t xdr_valuebuf (XDR *, valuebuf*);
extern  bool_t xdr_retbulkbuf (XDR *, retbulkbuf*);

#else /* K&R C */
extern bool_t xdr_msgbuf ();
extern bool_t xdr_msgtype ();
extern bool_t xdr_memdesc ();
extern bool_t xdr_mdtype ();
extern bool_t xdr_bulkbuf ();
extern bool_t xdr_bulktype ();
extern bool_t xdr_valuebuf ();
extern bool_t xdr_retbulkbuf ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
