/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "msg.h"

bool_t
xdr_msgbuf (XDR *xdrs, msgbuf *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->m_xlator, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->m_key, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->m_value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_msgtype (XDR *xdrs, msgtype *objp)
{
	register int32_t *buf;

	 if (!xdr_msgbuf (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_memdesc (XDR *xdrs, memdesc *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, &objp->mem_off))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->mem_size))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->mem_reserve))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mdtype (XDR *xdrs, mdtype *objp)
{
	register int32_t *buf;

	 if (!xdr_memdesc (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bulkbuf (XDR *xdrs, bulkbuf *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_uint32_t (xdrs, &objp->b_size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->b_bulk, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bulktype (XDR *xdrs, bulktype *objp)
{
	register int32_t *buf;

	 if (!xdr_bulkbuf (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_valuebuf (XDR *xdrs, valuebuf *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_msgtype (xdrs, &objp->valuebuf_u.retbuf))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_retbulkbuf (XDR *xdrs, retbulkbuf *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_bulktype (xdrs, &objp->retbulkbuf_u.retbuf))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
