/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "msg.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include "lwfs.h"
#include "xlator.h"
#include "common-utils.h"
#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

#ifndef GF_SWOS
xlator_t *sv_this=NULL;
#endif

static void
manager_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		msgtype getkeyvalue_2_arg;
		msgtype setkeyvalue_2_arg;
		mdtype getbulk_2_arg;
		msgtype getxlinfo_2_arg;
		int setdblevel_2_arg;
		int getopmask_2_arg;
		int setopmask_2_arg;
		int resetjob_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GETKEYVALUE:
		_xdr_argument = (xdrproc_t) xdr_msgtype;
		_xdr_result = (xdrproc_t) xdr_valuebuf;
		local = (char *(*)(char *, struct svc_req *)) getkeyvalue_2_svc;
		break;

	case SETKEYVALUE:
		_xdr_argument = (xdrproc_t) xdr_msgtype;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) setkeyvalue_2_svc;
		break;

	case GETBULK:
		_xdr_argument = (xdrproc_t) xdr_mdtype;
		_xdr_result = (xdrproc_t) xdr_retbulkbuf;
		local = (char *(*)(char *, struct svc_req *)) getbulk_2_svc;
		break;

	case GETXLINFO:
		_xdr_argument = (xdrproc_t) xdr_msgtype;
		_xdr_result = (xdrproc_t) xdr_retbulkbuf;
		local = (char *(*)(char *, struct svc_req *)) getxlinfo_2_svc;
		break;

	case GETSTATUS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) getstatus_2_svc;
		break;

	case GETDBLEVEL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) getdblevel_2_svc;
		break;

	case SETDBLEVEL:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) setdblevel_2_svc;
		break;

	case GETOPMASK:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) getopmask_2_svc;
		break;

	case SETOPMASK:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) setopmask_2_svc;
		break;

	case RESETJOB:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) resetjob_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		gf_log("server", GF_LOG_ERROR, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
server_start (void *data)
{
	register SVCXPRT *transp;

	pmap_unset (MANAGER, MANAGERVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		gf_log("server", GF_LOG_ERROR, "%s, %s", 
			"cannot create udp service.", strerror(errno));
		svcerr_systemerr (transp);
		exit(1);
	}
	if (!svc_register(transp, MANAGER, MANAGERVERS, manager_2, IPPROTO_UDP)) {
		gf_log("server", GF_LOG_ERROR, "%s, %s",
			 "unable to register (MANAGER, MANAGERVERS, udp).", strerror(errno));
		svcerr_systemerr (transp);
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		gf_log("server", GF_LOG_ERROR, "%s, %s", 
			"cannot create tcp service.", strerror(errno));
		svcerr_systemerr (transp);
		exit(1);
	}
	if (!svc_register(transp, MANAGER, MANAGERVERS, manager_2, IPPROTO_TCP)) {
		gf_log("server", GF_LOG_ERROR, "%s, %s", 
			"unable to register (MANAGER, MANAGERVERS, tcp).", strerror(errno));
		svcerr_systemerr (transp);
		exit(1);
	}

#ifndef GF_SWOS
        sv_this = data;
       	gf_log(sv_this->name, GF_LOG_ERROR, "data[%lx]", data);
#endif
	svc_run ();
	gf_log("server", GF_LOG_ERROR, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
