#!/bin/sh
### BEGIN INIT INFO
# Provides:          lwfsd
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: lw server
# Description:       This file starts / stops the lw server
### END INIT INFO

# Author: Chris AtLee <chris@atlee.ca>
# Patched by: Matthias Albert < matthias@linux4experts.de>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=lwfsd
SCRIPTNAME=/etc/init.d/$NAME
DAEMON=/usr/local/sbin/$NAME
PIDFILE=/var/run/$NAME.pid
CONFIGFILE=/etc/lwfs/lwfsd.vol
LWFS_OPTS="-f $CONFIGFILE"
PID=`test -f $PIDFILE && cat $PIDFILE`


# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
. /lib/lsb/init-functions

check_config()
{
  if [ ! -f "$CONFIGFILE" ]; then
    echo "Config file $CONFIGFILE is missing...exiting!"
    exit 0
  fi
}

do_start()
{
    check_config;
    pidofproc -p $PIDFILE $DAEMON >/dev/null
    status=$?
    if [ $status -eq 0 ]; then
      log_success_msg "lwfs server is already running with pid $PID"
    else
      log_daemon_msg "Starting lwfs server" "lwfsd"
      start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE $LWFS_OPTS
      log_end_msg $?
      start_daemon -p $PIDFILE $DAEMON -f $CONFIGFILE
      return $?
    fi
}

do_stop()
{
    log_daemon_msg "Stopping lwfs server" "lwfsd"
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    log_end_msg $?
    rm -f $PIDFILE
    killproc -p $PIDFILE $DAEMON
    return $?
}

do_status()
{
     pidofproc -p $PIDFILE $DAEMON >/dev/null
     status=$?
     if [ $status -eq 0 ]; then
       log_success_msg "lwfs server is running with pid $PID"
     else
       log_failure_msg "lwfs server is not running."
     fi
     exit $status
}

case "$1" in
  start)
        do_start
        ;;
  stop)
        do_stop
        ;;
  status)
        do_status;
        ;;
  restart|force-reload)
        do_stop
        sleep 2
        do_start
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
        exit 3
        ;;
esac

